# Generated by Django 6.0.2 on 2026-03-02 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField(blank=True, null=True)),
                ('ft_home_goals', models.IntegerField()),
                ('ft_away_goals', models.IntegerField()),
                ('ft_result', models.CharField(choices=[('H', 'Home Win'), ('A', 'Away Win'), ('D', 'Draw')], max_length=1)),
                ('ht_home_goals', models.IntegerField(blank=True, null=True)),
                ('ht_away_goals', models.IntegerField(blank=True, null=True)),
                ('ht_result', models.CharField(blank=True, choices=[('H', 'Home Win'), ('A', 'Away Win'), ('D', 'Draw')], max_length=1, null=True)),
                ('home_shots', models.IntegerField(blank=True, null=True)),
                ('away_shots', models.IntegerField(blank=True, null=True)),
                ('home_shots_on_target', models.IntegerField(blank=True, null=True)),
                ('away_shots_on_target', models.IntegerField(blank=True, null=True)),
                ('home_fouls', models.IntegerField(blank=True, null=True)),
                ('away_fouls', models.IntegerField(blank=True, null=True)),
                ('home_corners', models.IntegerField(blank=True, null=True)),
                ('away_corners', models.IntegerField(blank=True, null=True)),
                ('home_yellow_cards', models.IntegerField(blank=True, null=True)),
                ('away_yellow_cards', models.IntegerField(blank=True, null=True)),
                ('home_red_cards', models.IntegerField(blank=True, null=True)),
                ('away_red_cards', models.IntegerField(blank=True, null=True)),
                ('home_elo_pre', models.FloatField(blank=True, null=True)),
                ('away_elo_pre', models.FloatField(blank=True, null=True)),
                ('home_form_5', models.IntegerField(blank=True, null=True)),
                ('away_form_5', models.IntegerField(blank=True, null=True)),
                ('home_win_odds', models.FloatField(blank=True, null=True)),
                ('draw_odds', models.FloatField(blank=True, null=True)),
                ('away_win_odds', models.FloatField(blank=True, null=True)),
                ('over_2_5_odds', models.FloatField(blank=True, null=True)),
                ('under_2_5_odds', models.FloatField(blank=True, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='teams.league')),
            ],
            options={
                'unique_together': {('league', 'match_date', 'home_team', 'away_team')},
            },
        ),
    ]
