# Generated by Django 6.0.2 on 2026-03-05 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_club_team_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.club'),
        ),
    ]
